### ISSUE TITLE
Build error - binheap

### ISSUE THREAD

**Issue by Fullmono** [GuillaumeMCK/GhostYgg#17]
I have this error when I try to build the project
Do you know how to fix that?

> go version 1.21/armv6l

```
go build ./src/main.go
# github.com/lispad/go-generics-tools/binheap
../../go/pkg/mod/github.com/lispad/go-generics-tools@v1.1.0/binheap/topn.go:22:29: type func(x T, y T) bool of comparator does not match inferred type func(a T, b T) int for func(a E, b E) int
../../go/pkg/mod/github.com/lispad/go-generics-tools@v1.1.0/binheap/topstream.go:48:26: type func(x T, y T) bool of h.comparator does not match inferred type func(a T, b T) int for func(a E, b E) int
```

Regards,

**Comment by GuillaumeMCK** [comment]
Hi,
I wanted to inform you that this bug is related to the latest version of the torrent library, as discussed in this GitHub issue: [Link to Issue](https://github.com/anacrolix/torrent/issues/859). To resolve this, I have downgraded the library version in the `feat/tui-file-picker` branch. Since the project is still a work in progress (WIP), please be aware that other bugs and features may not have been implemented yet.

**Comment by GuillaumeMCK** [comment]
This issue has been fixed in the main branch
